//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AreaGov
{
    public int ID_Location { get; set; }
    public string AreaName { get; set; }
    public string GovernName { get; set; }
}

public partial class BlieverAction
{
    public BlieverAction()
    {
        this.BlieverUserClientActions = new HashSet<BlieverUserClientAction>();
    }

    public int B_ActionID { get; set; }
    public string ActionName { get; set; }
    public Nullable<System.DateTime> ARegDT { get; set; }

    public virtual ICollection<BlieverUserClientAction> BlieverUserClientActions { get; set; }
}

public partial class BlieverClientStage
{
    public BlieverClientStage()
    {
        this.BliverUserClients = new HashSet<BliverUserClient>();
    }

    public int CStageID { get; set; }
    public string StageName { get; set; }
    public Nullable<System.DateTime> SRegDT { get; set; }

    public virtual ICollection<BliverUserClient> BliverUserClients { get; set; }
}

public partial class BlieverUserClientAction
{
    public int BCA_ID { get; set; }
    public Nullable<int> BActionID { get; set; }
    public string BCcomment { get; set; }
    public Nullable<System.DateTime> BCRegDT { get; set; }
    public Nullable<int> CStageID { get; set; }
    public Nullable<int> BID { get; set; }
    public Nullable<int> CID { get; set; }

    public virtual BlieverAction BlieverAction { get; set; }
    public virtual BliverUser BliverUser { get; set; }
    public virtual Client Client { get; set; }
}

public partial class BliverProject
{
    public int Proj_ID { get; set; }
    public string DeveloperName { get; set; }
    public string location { get; set; }
    public Nullable<int> AreaID { get; set; }
    public string OwnerName { get; set; }
    public string workhistory { get; set; }
    public string pricing { get; set; }
    public string featurefasultes { get; set; }
    public string Deposet1 { get; set; }
    public string PaymentMethod1 { get; set; }
    public string InstallmentValue1 { get; set; }
    public string Deposet2 { get; set; }
    public string PaymentMethod2 { get; set; }
    public string InstallmentValue2 { get; set; }
    public string Deposet3 { get; set; }
    public string PaymentMethod3 { get; set; }
    public string InstallmentValue3 { get; set; }
    public string ResponsPersonal { get; set; }
    public string MobileNumber { get; set; }
}

public partial class BliverUser
{
    public BliverUser()
    {
        this.BliverUserClients = new HashSet<BliverUserClient>();
        this.ClientNotes = new HashSet<ClientNote>();
        this.ClientDetails = new HashSet<ClientDetail>();
        this.BlieverUserClientActions = new HashSet<BlieverUserClientAction>();
    }

    public int BlieverID { get; set; }
    public string BliverUserName { get; set; }
    public string BliverPassword { get; set; }
    public Nullable<int> BliverLevel { get; set; }
    public Nullable<int> BliverCompID { get; set; }
    public Nullable<bool> BliverFlag { get; set; }
    public Nullable<System.DateTime> RegDT { get; set; }
    public Nullable<System.DateTime> BliveruserUpdateDt { get; set; }
    public string BliverFullName { get; set; }
    public string BliverEmail { get; set; }
    public string BliverGender { get; set; }
    public string BliverMob { get; set; }
    public Nullable<System.DateTime> BliverBirthdate { get; set; }

    public virtual Company Company { get; set; }
    public virtual ICollection<BliverUserClient> BliverUserClients { get; set; }
    public virtual ICollection<ClientNote> ClientNotes { get; set; }
    public virtual ICollection<ClientDetail> ClientDetails { get; set; }
    public virtual ICollection<BlieverUserClientAction> BlieverUserClientActions { get; set; }
}

public partial class BliverUserClient
{
    public int BCID { get; set; }
    public Nullable<int> BliverUserID { get; set; }
    public Nullable<int> BliverClientID { get; set; }
    public Nullable<int> BliverCompanyID { get; set; }
    public Nullable<bool> BCFlag { get; set; }
    public Nullable<System.DateTime> BCRegDT { get; set; }
    public Nullable<int> BCCatid { get; set; }
    public Nullable<int> BUCStage { get; set; }

    public virtual BliverUser BliverUser { get; set; }
    public virtual Client Client { get; set; }
    public virtual ClientCategory ClientCategory { get; set; }
    public virtual Company Company { get; set; }
    public virtual BlieverClientStage BlieverClientStage { get; set; }
}

public partial class Client
{
    public Client()
    {
        this.BliverUserClients = new HashSet<BliverUserClient>();
        this.ClientNotes = new HashSet<ClientNote>();
        this.ClientDetails = new HashSet<ClientDetail>();
        this.BlieverUserClientActions = new HashSet<BlieverUserClientAction>();
    }

    public int ClientID { get; set; }
    public string ClientName { get; set; }
    public string ClientMob { get; set; }
    public string ClientAddress { get; set; }
    public string ClientEmail { get; set; }
    public string AreaIntersted { get; set; }
    public Nullable<int> ClientStageID { get; set; }
    public Nullable<int> CompanyID { get; set; }
    public Nullable<bool> status { get; set; }
    public Nullable<System.DateTime> Regdatetime { get; set; }
    public string HomeTown { get; set; }
    public string jobTitle { get; set; }
    public string Education { get; set; }
    public string Gender { get; set; }
    public Nullable<System.DateTime> Birthdate { get; set; }
    public string WorkPlace { get; set; }
    public Nullable<int> Clientcat { get; set; }
    public int ClientCode { get; set; }

    public virtual ICollection<BliverUserClient> BliverUserClients { get; set; }
    public virtual ClientCategory ClientCategory { get; set; }
    public virtual Company Company { get; set; }
    public virtual ICollection<ClientNote> ClientNotes { get; set; }
    public virtual ClientCategory ClientCategory1 { get; set; }
    public virtual ICollection<ClientDetail> ClientDetails { get; set; }
    public virtual ICollection<BlieverUserClientAction> BlieverUserClientActions { get; set; }
}

public partial class ClientCategory
{
    public ClientCategory()
    {
        this.Clients = new HashSet<Client>();
        this.BliverUserClients = new HashSet<BliverUserClient>();
        this.Clients1 = new HashSet<Client>();
    }

    public int CatID { get; set; }
    public string Category { get; set; }
    public Nullable<bool> Status { get; set; }

    public virtual ICollection<Client> Clients { get; set; }
    public virtual ICollection<BliverUserClient> BliverUserClients { get; set; }
    public virtual ICollection<Client> Clients1 { get; set; }
}

public partial class ClientDetail
{
    public int ClientDetailsID { get; set; }
    public Nullable<int> ClientID { get; set; }
    public Nullable<int> CompanyID { get; set; }
    public Nullable<int> BliverUserID { get; set; }
    public string InterstingProject1 { get; set; }
    public string InterstingProject2 { get; set; }
    public string InterstingProject3 { get; set; }
    public string ClientBadget { get; set; }
    public Nullable<System.DateTime> ClientAddedDate { get; set; }
    public string InterestingUnit { get; set; }
    public string SalesOfficerProject { get; set; }
    public string MasterDecision { get; set; }
    public string PurchasingPower { get; set; }
    public string VisitPlace { get; set; }
    public Nullable<System.DateTime> CDRegDateTime { get; set; }
    public Nullable<System.DateTime> CDUpdateDateTime { get; set; }

    public virtual BliverUser BliverUser { get; set; }
    public virtual Client Client { get; set; }
    public virtual Company Company { get; set; }
}

public partial class ClientNote
{
    public int ClientNoteID { get; set; }
    public Nullable<int> ClientID { get; set; }
    public Nullable<int> BliverUserID { get; set; }
    public string Note { get; set; }
    public Nullable<System.DateTime> NoteRegDt { get; set; }
    public Nullable<System.DateTime> NoteUpdateDT { get; set; }
    public Nullable<int> BliverCompanyID { get; set; }

    public virtual BliverUser BliverUser { get; set; }
    public virtual Client Client { get; set; }
}

public partial class Company
{
    public Company()
    {
        this.BliverUsers = new HashSet<BliverUser>();
        this.Clients = new HashSet<Client>();
        this.BliverUserClients = new HashSet<BliverUserClient>();
        this.ClientDetails = new HashSet<ClientDetail>();
    }

    public int CompanyID { get; set; }
    public string CompanyName { get; set; }
    public Nullable<bool> CompanyFlag { get; set; }

    public virtual ICollection<BliverUser> BliverUsers { get; set; }
    public virtual ICollection<Client> Clients { get; set; }
    public virtual ICollection<BliverUserClient> BliverUserClients { get; set; }
    public virtual ICollection<ClientDetail> ClientDetails { get; set; }
}

public partial class Employee
{
    public int EmpID { get; set; }
    public string EmpName { get; set; }
    public string EmpTitle { get; set; }
    public Nullable<int> EmpCompID { get; set; }
    public Nullable<bool> Flag { get; set; }
}

public partial class Evaluation
{
    public int EvaluationID { get; set; }
    public string EvaluationName { get; set; }
}

public partial class EvalutionPoint
{
    public int EvaPointID { get; set; }
    public string PointQuistion { get; set; }
    public string EvalutionName { get; set; }
    public Nullable<int> EvalutionID { get; set; }
}

public partial class GalleryImage
{
    public int ImageID { get; set; }
    public string ImageURL { get; set; }
    public Nullable<bool> ImageFlag { get; set; }
    public string ImageProject { get; set; }
    public Nullable<System.DateTime> ImageRegDate { get; set; }
    public string ImageRegUser { get; set; }
    public string imagesection { get; set; }
}

public partial class HiredApplication
{
    public int HireApplicationID { get; set; }
    public string AppName { get; set; }
    public string AppEmail { get; set; }
    public string AppMobile { get; set; }
    public string AppAddress { get; set; }
    public Nullable<int> HirePostID { get; set; }
    public Nullable<System.DateTime> AppDateTime { get; set; }
    public string Status { get; set; }
    public string AppCvs { get; set; }
}

public partial class HirePost
{
    public int HirePostID { get; set; }
    public string HireTitle { get; set; }
    public string HireJobDes { get; set; }
    public string HireJobCode { get; set; }
    public Nullable<System.DateTime> ExpDateTime { get; set; }
    public Nullable<bool> HireFlag { get; set; }
}

public partial class HireWithU
{
    public int HWUsID { get; set; }
    public string CompName { get; set; }
    public string JobTitle { get; set; }
    public string JobDesc { get; set; }
    public Nullable<System.DateTime> ExpDate { get; set; }
    public string CompEmail { get; set; }
    public string ContactPersonalName { get; set; }
    public string ContactPersonalMob { get; set; }
    public string SecoundContactperName { get; set; }
    public string SecoundContactperMob { get; set; }
    public string ApplicationFile { get; set; }
}

public partial class MonthlyScore
{
    public int MonthlyScoreID { get; set; }
    public Nullable<int> EmpID { get; set; }
    public string Score { get; set; }
    public string Month { get; set; }
    public string presentage { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class Team
{
    public int TeamID { get; set; }
    public string Name { get; set; }
    public string Title { get; set; }
}

public partial class User
{
    public int UserID { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string Role { get; set; }
    public Nullable<int> CompanyID { get; set; }
    public Nullable<bool> UserFlag { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}
